Log de errores:
1. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). ... In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

1.a https://til.hashrocket.com/posts/aucwkd8b36-asyncawait-unhandledpromiserejectionwarning

